apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: cloudbankdb
  namespace: cloudbank
spec:
  details:
    autonomousDatabaseOCID: ocid1.autonomousdatabase.oc1.ap-mumbai-1.anrg6ljry5l3z3yahhpdzfnpd2hcrj7zwgvvhyieiqp33opvax7rcinvbt6q
    cpuCoreCount: 1
    isAutoScalingEnabled: false