apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: cloudbankdb
  namespace: cloudbank
spec:
  details:
    compartmentOCID: ocid1.compartment.oc1..aaaaaaaaqhbzavhpwjjlcf43lgkjhhz2qbztfh6xbav24x7kfaxrtxvmgyra
    dbName: cbdb64qgtiio
    displayName: cloudbankdb_cbdb64qgtiio
    cpuCoreCount: 1
    adminPassword:
      k8sSecret:
        name: admin-password

    dataStorageSizeInTBs: 1